"""add_google_sign_in_and_tracking_fields

Revision ID: 757b5a8de7c0
Revises: f09074e34415
Create Date: 2026-08-16 19:30:04.562943

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '757b5a8de7c0'
down_revision = 'f09074e34415'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('empresa_transporte', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('numero_guia', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('numero_guia_foto_url', sa.String(length=255), nullable=True))

    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.add_column(sa.Column('google_id', sa.String(length=150), nullable=True))
        batch_op.create_unique_constraint(None, ['google_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('usuarios', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('google_id')

    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.drop_column('numero_guia_foto_url')
        batch_op.drop_column('numero_guia')
        batch_op.drop_column('empresa_transporte')

    # ### end Alembic commands ###
