"""Sincronizacion final

Revision ID: f09074e34415
Revises: 
Create Date: 2026-08-13 17:01:51.925123

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f09074e34415'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('configuracion_empresa', schema=None) as batch_op:
        batch_op.add_column(sa.Column('margen_ganancia_mayorista', sa.Numeric(precision=10, scale=2), nullable=False))
        batch_op.add_column(sa.Column('tipo_cambio_usd', sa.Numeric(precision=10, scale=4), nullable=True))
        batch_op.add_column(sa.Column('tipo_cambio_actualizado', sa.DateTime(), nullable=True))

    with op.batch_alter_table('items_pedido', schema=None) as batch_op:
        batch_op.add_column(sa.Column('precio_unitario_usd', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('precio_compra_unitario_usd', sa.Numeric(precision=10, scale=2), nullable=True))
        batch_op.add_column(sa.Column('nivel_precio', sa.String(length=20), nullable=False))
        batch_op.drop_column('tipo_tarifa')

    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nivel_precio', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('metodo_envio_nombre', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('costo_envio', sa.Numeric(precision=10, scale=2), nullable=False))
        batch_op.add_column(sa.Column('tipo_cambio_aplicado', sa.Numeric(precision=10, scale=4), nullable=True))
        batch_op.drop_column('tipo_tarifa')

    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.alter_column('precio_compra_usd',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
        batch_op.alter_column('tipo_cambio_al_comprar',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.Numeric(precision=10, scale=4),
               existing_nullable=True)
        batch_op.alter_column('precio_minorista_usd',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
        batch_op.alter_column('precio_mayorista_usd',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
        batch_op.alter_column('precio_franquicia_usd',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
        batch_op.alter_column('precio_asesora_libre_usd',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=False)
        batch_op.alter_column('minorista_habilitado',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
        batch_op.alter_column('mayorista_habilitado',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
        batch_op.alter_column('franquicia_habilitado',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
        batch_op.alter_column('asesora_libre_habilitado',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
        batch_op.drop_column('precio_minorista')
        batch_op.drop_column('precio_mayorista')
        batch_op.drop_column('precio_publico')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('productos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('precio_publico', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('precio_mayorista', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('precio_minorista', sa.NUMERIC(precision=10, scale=2), autoincrement=False, nullable=False))
        batch_op.alter_column('asesora_libre_habilitado',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
        batch_op.alter_column('franquicia_habilitado',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
        batch_op.alter_column('mayorista_habilitado',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
        batch_op.alter_column('minorista_habilitado',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
        batch_op.alter_column('precio_asesora_libre_usd',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
        batch_op.alter_column('precio_franquicia_usd',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
        batch_op.alter_column('precio_mayorista_usd',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
        batch_op.alter_column('precio_minorista_usd',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)
        batch_op.alter_column('tipo_cambio_al_comprar',
               existing_type=sa.Numeric(precision=10, scale=4),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=True)
        batch_op.alter_column('precio_compra_usd',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               nullable=True)

    with op.batch_alter_table('pedidos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo_tarifa', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
        batch_op.drop_column('tipo_cambio_aplicado')
        batch_op.drop_column('costo_envio')
        batch_op.drop_column('metodo_envio_nombre')
        batch_op.drop_column('nivel_precio')

    with op.batch_alter_table('items_pedido', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tipo_tarifa', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
        batch_op.drop_column('nivel_precio')
        batch_op.drop_column('precio_compra_unitario_usd')
        batch_op.drop_column('precio_unitario_usd')

    with op.batch_alter_table('configuracion_empresa', schema=None) as batch_op:
        batch_op.drop_column('tipo_cambio_actualizado')
        batch_op.drop_column('tipo_cambio_usd')
        batch_op.drop_column('margen_ganancia_mayorista')

    # ### end Alembic commands ###
